server:
  port:
    9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goldfish?serverTimezone=GMT%2b8
    username: root
    password: admin123


mvc:
  pathmatch:
    matching-strategy=ant_path_matcher:mybatis:
    matching-strategy: ant_path_matcher
    mapper-locations: classpath:mapper/*.xml #扫描所有mybatis文件






